import { createMultilineString } from '../../../utils/text-utils';

export const classDeclarationTestSnippet = createMultilineString(
    '// non-blank line',
    'export abstract class Foo extends Bar {',
    '  // properties',
    '',
    '  // methods',
    '}',
    '// non-blank line',
    'export class VeryLongClassName<TYPE extends SomeType>',
    '  implements EvenLongerInterfaceName<SomeMonstrouslyLongName> {',
    '  // properties',
    '',
    '  // methods',
    '}',
    '// non-blank line',
    '  @Component({',
    '    selector: "app-indented-foo",',
    '  })',
    '  class IndentedFoo implements OnInit {',
    '    // implementation',
    '  }',
    '// non-blank line',
    '@Component({ selector: "app-bar" })',
    'class Bar implements OnInit {',
    '  // implementation',
    '}',
    '// non-blank line',
    '@Injectable()',
    'export class Baz {',
    '  // implementation',
    '}',
    '// non-blank line',
);
