import { createMultilineString } from '../../../utils/text-utils';

export const unitTestHookStatementTestSnippet = createMultilineString(
    'describe("first test suite", () => {',
    '  // non-blank line',
    '  before(() => {',
    '    // code',
    '  });',
    '  // non-blank line',
    '  beforeEach(async () => {',
    '    // regular ES6 async',
    '  });',
    '  // non-blank line',
    '  beforeEach(async(() => {',
    '    // Angular async',
    '  }));',
    '  // non-blank line',
    '  beforeAll(() => {',
    '    // code',
    '  });',
    '  // non-blank line',
    '  after(() => {',
    '    // code',
    '  });',
    '  // non-blank line',
    '  afterEach(() => {',
    '    // code',
    '  });',
    '  // non-blank line',
    '  afterAll(() => {',
    '    // code',
    '  });',
    '  // non-blank line',
    '});',
);
