import { createMultilineString } from '../../../../utils/text-utils';

export const unitTestDescribeBlockPlaceholderSnippet = createMultilineString(
    '// non-blank line',
    '%BLANK_BEFORE%',
    'describe("top-level test suite", () => {',
    '  // tests',
    '});',
    '%BLANK_AFTER%',
    '// non-blank line',
    '%BLANK_BEFORE%',
    'describe("another top-level test suite", () => {',
    '%BLANK_BEFORE%',
    '%IND%describe("first level nested test suite", () => {',
    '%BLANK_BEFORE%',
    '%IND%%IND%describe("second level nested test suite", () => {',
    '%BLANK_BEFORE%',
    '%IND%%IND%%IND%describe("third level nested test suite", () => {',
    '%IND%%IND%%IND%%IND%// tests',
    '%IND%%IND%%IND%%IND%',
    '%IND%%IND%%IND%%IND%// more tests',
    '%IND%%IND%%IND%});',
    '%BLANK_AFTER%',
    '%IND%%IND%});',
    '%BLANK_AFTER%',
    '%IND%});',
    '%BLANK_AFTER%',
    '%IND%// non-blank line',
    '%BLANK_BEFORE%',
    '%IND%describe("another first level nested test suite", () => {',
    '%IND%%IND%// tests',
    '%IND%});',
    '%BLANK_AFTER%',
    '});',
    '%BLANK_AFTER%',
    '// non-blank line',
);
