import { createMultilineString } from '../../../../utils/text-utils';

export const unitTestHookStatementSnippet = createMultilineString(
    'describe("first test suite", () => {',
    '  // non-blank line',
    '%BLANK_BEFORE%',
    '  before(() => {',
    '    // code',
    '  });',
    '%BLANK_AFTER%',
    '  // non-blank line',
    '%BLANK_BEFORE%',
    '  beforeEach(async () => {',
    '    // regular ES6 async',
    '  });',
    '%BLANK_AFTER%',
    '  // non-blank line',
    '%BLANK_BEFORE%',
    '  beforeEach(async(() => {',
    '    // Angular async',
    '  }));',
    '%BLANK_AFTER%',
    '  // non-blank line',
    '%BLANK_BEFORE%',
    '  beforeAll(() => {',
    '    // code',
    '  });',
    '%BLANK_AFTER%',
    '  // non-blank line',
    '%BLANK_BEFORE%',
    '  after(() => {',
    '    // code',
    '  });',
    '%BLANK_AFTER%',
    '  // non-blank line',
    '%BLANK_BEFORE%',
    '  afterEach(() => {',
    '    // code',
    '  });',
    '%BLANK_AFTER%',
    '  // non-blank line',
    '%BLANK_BEFORE%',
    '  afterAll(() => {',
    '    // code',
    '  });',
    '%BLANK_AFTER%',
    '  // non-blank line',
    '});',
);
